<?php
$mapStyle['dynamic'] = "[{'featureType':'all','elementType':'labels','stylers':[{'visibility':'on'}]},{'featureType':'all','elementType':'labels.text.fill','stylers':[{'saturation':36},{'color':'#000000'},{'lightness':40}]},{'featureType':'all','elementType':'labels.text.stroke','stylers':[{'visibility':'on'},{'color':'#000000'},{'lightness':16}]},{'featureType':'all','elementType':'labels.icon','stylers':[{'visibility':'off'}]},{'featureType':'administrative','elementType':'geometry.fill','stylers':[{'color':'#000000'},{'lightness':20}]},{'featureType':'administrative','elementType':'geometry.stroke','stylers':[{'color':'#000000'},{'lightness':17},{'weight':1.2}]},{'featureType':'administrative.locality','elementType':'labels.text.fill','stylers':[{'color':'#c4c4c4'}]},{'featureType':'administrative.neighborhood','elementType':'labels.text.fill','stylers':[{'color':'#707070'}]},{'featureType':'landscape','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':20}]},{'featureType':'landscape.man_made','elementType':'all','stylers':[{'color':'#555555'}]},{'featureType':'landscape.natural','elementType':'geometry','stylers':[{'color':'#989898'}]},{'featureType':'poi','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':21},{'visibility':'on'}]},{'featureType':'poi.business','elementType':'geometry','stylers':[{'visibility':'on'}]},{'featureType':'road.highway','elementType':'geometry.fill','stylers':[{'color':'#c3060d'},{'lightness':'0'},{'visibility':'on'}]},{'featureType':'road.highway','elementType':'geometry.stroke','stylers':[{'visibility':'off'}]},{'featureType':'road.highway','elementType':'labels.text.fill','stylers':[{'visibility':'off'}]},{'featureType':'road.highway','elementType':'labels.text.stroke','stylers':[{'visibility':'off'},{'hue':'#ff000a'}]},{'featureType':'road.arterial','elementType':'all','stylers':[{'color':'#ee1010'}]},{'featureType':'road.arterial','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':18}]},{'featureType':'road.arterial','elementType':'geometry.fill','stylers':[{'color':'#575757'}]},{'featureType':'road.arterial','elementType':'labels.text.fill','stylers':[{'color':'#ffffff'}]},{'featureType':'road.arterial','elementType':'labels.text.stroke','stylers':[{'color':'#2c2c2c'}]},{'featureType':'road.local','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':16}]},{'featureType':'road.local','elementType':'labels.text.fill','stylers':[{'color':'#999999'}]},{'featureType':'road.local','elementType':'labels.text.stroke','stylers':[{'saturation':'-52'}]},{'featureType':'transit','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':19}]},{'featureType':'transit.station.rail','elementType':'all','stylers':[{'visibility':'on'}]},{'featureType':'water','elementType':'geometry','stylers':[{'color':'#000000'},{'lightness':17}]}]"; 
			
$mapStyle['static'] = 'feature:administrative%7Celement:geometry%7Ccolor:0xa7a7a7&style=feature:administrative%7Celement:labels.text.fill%7Ccolor:0x737373%7Cvisibility:on&style=feature:landscape%7Celement:geometry.fill%7Ccolor:0xefefef%7Cvisibility:on&style=feature:landscape.man_made%7Cvisibility:off&style=feature:landscape.natural.landcover%7Cvisibility:off&style=feature:landscape.natural.terrain%7Cvisibility:off&style=feature:poi%7Celement:geometry.fill%7Ccolor:0xdadada%7Cvisibility:off&style=feature:poi%7Celement:labels%7Cvisibility:off&style=feature:poi%7Celement:labels.icon%7Cvisibility:off&style=feature:poi.attraction%7Ccolor:0xe18aa5%7Cvisibility:off&style=feature:poi.attraction%7Celement:geometry%7Cvisibility:off&style=feature:poi.attraction%7Celement:labels%7Cvisibility:off&style=feature:poi.attraction%7Celement:labels.text%7Ccolor:0x897c7c&style=feature:poi.attraction%7Celement:labels.text.fill%7Cvisibility:off&style=feature:poi.attraction%7Celement:labels.text.stroke%7Cvisibility:on&style=feature:road%7Celement:labels.icon%7Cvisibility:off&style=feature:road%7Celement:labels.text.fill%7Ccolor:0x696969&style=feature:road.arterial%7Celement:geometry.fill%7Ccolor:0xffffff&style=feature:road.arterial%7Celement:geometry.stroke%7Ccolor:0xd6d6d6%7Cvisibility:off&style=feature:road.highway%7Celement:geometry.fill%7Ccolor:0xd9d9d9&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0xb9b9b9%7Cvisibility:on&style=feature:road.local%7Celement:geometry.fill%7Ccolor:0xffffff%7Cvisibility:on%7Cweight:1.8&style=feature:road.local%7Celement:geometry.stroke%7Ccolor:0xd7d7d7%7Cvisibility:off&style=feature:transit%7Ccolor:0x808080%7Cvisibility:off&style=feature:water%7Csaturation:100%7Cvisibility:on&style=feature:water%7Celement:geometry%7Csaturation:-63%7Clightness:53%7Cvisibility:on&style=feature:water%7Celement:geometry.fill%7Ccolor:0xd4d4d3&style=feature:water%7Celement:geometry.stroke%7Cvisibility:off&style=feature:water%7Celement:labels%7Cvisibility:off&style=feature:water%7Celement:labels.icon%7Csaturation:-75%7Clightness:61%7Cvisibility:on&style=feature:water%7Celement:labels.text%7Ccolor:0x6a6a6a%7Cvisibility:on&style=feature:water%7Celement:labels.text.fill%7Ccolor:0x7c7c7c%7Cvisibility:off'; 
$mapStyle['bing'] = "elements: {
area: { fillColor: '#dadada' },
water: { fillColor: '#d3d3d3',labelVisible: true, labelColor: '#6c96cf' },
majorRoad:{fillColor:'#d5d5d5', strokeColor: '#c7c7c7', labelColor: '#6c96cf'},
tollRoad: { fillColor: '#ffffff', strokeColor: '#b3b3b3', labelColor: '#6c96cf', labelVisible: false},
arterialRoad: { fillColor: '#ffffff', strokeColor: '#d7dae7', labelColor: '#6c96cf'}, 
controlledAccessHighway: { fillColor: '#ffffff', strokeColor: '#b3b3b3', labelColor: '#6c96cf',labelVisible: false}, 
highway: { fillColor: '#ffffff', strokeColor: '#b3b3b3', labelColor: '#025894', labelVisible: false }, 
road: { fillColor: '#696969', strokeColor: '#f696969', labelColor: '#6c96cf'}, 
street: { fillColor: '#ffffff', strokeColor: '#ffffff', labelColor: '#6c96cf'}, 
	transit: { fillColor: '#808080', strokeColor: '#c2c2c2', labelColor: '#6c96cf' } 
}, 
settings: { 
	landColor: '#efefef' 
}"; 
?>